import { cleanup, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import Gallery, { openGalleryComparison, resetGallerySession } from "./Gallery";
import { api } from "./api";

describe("galeria em escala",()=>{
 afterEach(()=>{cleanup();resetGallerySession();localStorage.clear();vi.restoreAllMocks()});
 it("mostra indicadores e aplica filtros combinados",async()=>{const user=userEvent.setup();const spy=vi.spyOn(api,"gallery");render(<Gallery/>);expect(await screen.findByText("18")).toBeInTheDocument();expect(screen.getByText("Em várias origens")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:/Filtros/}));await user.selectOptions(screen.getByLabelText("Tipo"),"video");await user.selectOptions(screen.getByLabelText("Câmera"),"DJI Mini 4 Pro");await user.click(screen.getByRole("button",{name:"Aplicar filtros"}));await waitFor(()=>expect(spy).toHaveBeenLastCalledWith(expect.objectContaining({mediaType:"video",camera:"DJI Mini 4 Pro"}),undefined,100,"captured_desc"));expect(screen.getByText(/resultados/)).toBeInTheDocument()});
 it("mantém o cabeçalho natural e não polui o grid com proteção pendente",async()=>{render(<Gallery/>);expect((await screen.findAllByText(/^[A-ZÁÉÍÓÚÂÊÔÃÕÇ][^\n]+ de \d{4}$/)).length).toBeGreaterThan(0);expect(screen.queryByText("Proteção pendente")).not.toBeInTheDocument()});
 it("usa a miniatura real também no preview sem a faixa inferior",async()=>{const user=userEvent.setup();vi.spyOn(api,"thumbnail").mockResolvedValue("data:image/jpeg;base64,AA==");render(<Gallery/>);await user.click(await screen.findByRole("button",{name:"Abrir detalhes de IMG_2401.JPG"}));expect(await screen.findByText("SHA-256")).toBeInTheDocument();await waitFor(()=>expect(document.querySelector(".preview-stage img")).toHaveAttribute("src","data:image/jpeg;base64,AA=="));expect(screen.queryByLabelText("Mídias próximas")).not.toBeInTheDocument()});
 it("mantém o preview sincronizado ao navegar",async()=>{const user=userEvent.setup();render(<Gallery/>);await user.click(await screen.findByRole("button",{name:"Abrir detalhes de IMG_2401.JPG"}));expect(screen.getByText("2 de 18")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Próxima mídia"}));expect(await screen.findByRole("heading",{name:"IMG_2402.JPG"})).toBeInTheDocument();await user.keyboard("{ArrowLeft}");expect(await screen.findByRole("heading",{name:"IMG_2401.JPG"})).toBeInTheDocument()});
 it("troca o arquivo real e os metadados junto com a foto",async()=>{const user=userEvent.setup();vi.spyOn(api,"mediaUrl").mockImplementation(async id=>`http://lumina-media.localhost/${id}`);vi.spyOn(api,"assetDetails").mockImplementation(async id=>({detectedFormat:"JPEG",mime:"image/jpeg",lens:id==="demo-1"?"Lente A":"Lente B",iso:100,aperture:2.8,exposure:"0.004",focalLength:35}));render(<Gallery/>);await user.click(await screen.findByRole("button",{name:"Abrir detalhes de IMG_2401.JPG"}));expect(await screen.findByRole("img",{name:"Prévia de IMG_2401.JPG"})).toHaveAttribute("src","http://lumina-media.localhost/demo-1");expect(await screen.findByText("Lente A")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Próxima mídia"}));expect(await screen.findByRole("img",{name:"Prévia de IMG_2402.JPG"})).toHaveAttribute("src","http://lumina-media.localhost/demo-2");expect(await screen.findByText("Lente B")).toBeInTheDocument()});
 it("substitui a miniatura pela prévia HD produzida sob demanda",async()=>{const user=userEvent.setup();vi.spyOn(api,"mediaUrl").mockResolvedValue("http://lumina-media.localhost/demo-1");const high=vi.spyOn(api,"photoPreview").mockResolvedValue("http://lumina-preview.localhost/demo-1");render(<Gallery/>);await user.click(await screen.findByRole("button",{name:"Abrir detalhes de IMG_2401.JPG"}));expect(await screen.findByRole("img",{name:"Prévia de IMG_2401.JPG"})).toHaveAttribute("src","http://lumina-preview.localhost/demo-1");expect(screen.getByText("Prévia HD")).toBeInTheDocument();expect(high).toHaveBeenCalledWith("demo-1")});
 it("continua navegável enquanto a miniatura é produzida em background",async()=>{const user=userEvent.setup();const thumbnail=vi.spyOn(api,"thumbnail").mockResolvedValueOnce(null).mockResolvedValue("http://lumina-thumb.localhost/demo-1");render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:/Filtros/}));expect(screen.getByRole("button",{name:"Aplicar filtros"})).toBeEnabled();expect(await screen.findByRole("img",{name:"Prévia de IMG_2401.JPG"},{timeout:2000})).toHaveAttribute("src","http://lumina-thumb.localhost/demo-1");expect(thumbnail.mock.calls.length).toBeGreaterThanOrEqual(2)});
 it("alterna para lista e persiste a preferência",async()=>{const user=userEvent.setup();const first=render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:"Visão em lista"}));expect(document.querySelector(".virtual-gallery.list")).toBeInTheDocument();expect(localStorage.getItem("lumina-view")).toBe("list");first.unmount();render(<Gallery/>);await waitFor(()=>expect(document.querySelector(".virtual-gallery.list")).toBeInTheDocument())});
 it("apresenta lista com colunas estáveis e dados operacionais",async()=>{const user=userEvent.setup();render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:"Visão em lista"}));expect(screen.getByText("Captura")).toBeInTheDocument();expect(screen.getByText("Arquivo")).toBeInTheDocument();expect(screen.getByText("Origem")).toBeInTheDocument();expect(screen.getByText("Proteção")).toBeInTheDocument();expect(document.querySelector(".media-card.list-row")).toBeInTheDocument()});
 it("integra o inspetor ao workspace sem cobrir a galeria",async()=>{const user=userEvent.setup();render(<Gallery/>);await user.click(await screen.findByRole("button",{name:"Abrir detalhes de IMG_2401.JPG"}));expect(document.querySelector(".gallery-workspace.inspector-open")).toBeInTheDocument();expect(screen.getByRole("complementary",{name:"Detalhes da mídia"})).toBeInTheDocument();expect(screen.getByLabelText("Acervo de mídias")).toBeInTheDocument()});
 it("simplifica os metadados do inspetor",async()=>{const user=userEvent.setup();render(<Gallery/>);await user.click(await screen.findByRole("button",{name:"Abrir detalhes de IMG_2401.JPG"}));expect(screen.queryByText("Data obtida de")).not.toBeInTheDocument();expect(screen.queryByText("MIME")).not.toBeInTheDocument();expect(screen.queryByText("Perfil de cor")).not.toBeInTheDocument();expect(screen.queryByText("Orientação")).not.toBeInTheDocument()});
 it("envia ordenação persistente ao backend",async()=>{const user=userEvent.setup();const spy=vi.spyOn(api,"gallery");render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:"Ordenar"}));await user.click(screen.getByRole("option",{name:"Nome A–Z"}));await waitFor(()=>expect(spy).toHaveBeenLastCalledWith(expect.anything(),undefined,100,"name_asc"));expect(localStorage.getItem("lumina-sort")).toBe("name_asc")});
 it("abre comparação somente com duas mídias",async()=>{const user=userEvent.setup();render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:"Selecionar IMG_2401.JPG"}));await user.click(screen.getByRole("button",{name:"Selecionar IMG_2402.JPG"}));await user.click(screen.getByRole("button",{name:"Comparar"}));expect(screen.getByRole("dialog",{name:"Comparar mídias"})).toBeInTheDocument();expect(screen.getAllByText("IMG_2401.JPG").length).toBeGreaterThan(0)});
 it("persiste densidade própria da lista",async()=>{const user=userEvent.setup();render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:"Visão em lista"}));await user.click(screen.getByRole("button",{name:"Densidade da lista"}));await user.click(screen.getByRole("option",{name:"Compacta"}));expect(document.querySelector(".virtual-gallery.density-compact")).toBeInTheDocument();expect(localStorage.getItem("lumina-list-density")).toBe("compact")});
 it("prioriza miniaturas visíveis em lotes limitados",async()=>{const prefetch=vi.spyOn(api,"prefetchThumbnails");render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await waitFor(()=>expect(prefetch).toHaveBeenCalledWith(expect.any(Array),180));expect(prefetch.mock.calls.every(call=>call[0].length<=80)).toBe(true)});
 it("persiste seções de metadados e abre localização sob demanda",async()=>{const user=userEvent.setup();const reveal=vi.spyOn(api,"revealAsset");render(<Gallery/>);await user.click(await screen.findByRole("button",{name:"Abrir detalhes de IMG_2401.JPG"}));const capture=screen.getByText("Captura").closest("summary")!;await user.click(capture);expect(localStorage.getItem("lumina-metadata-capture")).toBe("closed");await user.click(screen.getByRole("button",{name:/Abrir localização/}));expect(reveal).toHaveBeenCalledWith("demo-1")});
 it("seleciona mídias, mostra o highlight e aplica tag em lote",async()=>{const user=userEvent.setup();const apply=vi.spyOn(api,"applyTag");render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:"Selecionar IMG_2401.JPG"}));expect(screen.getByText("1 selecionadas")).toBeInTheDocument();expect(screen.getByText("Selecionado")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Aplicar tag"}));await user.type(screen.getByLabelText("Nome da tag"),"favorita");await user.click(screen.getByRole("button",{name:"Aplicar"}));await waitFor(()=>expect(apply).toHaveBeenCalledWith("favorita",["demo-1"]));expect(await screen.findByRole("status")).toHaveTextContent("1 mídias atualizadas")});
 it("abre a comparação iniciada por uma descoberta",async()=>{openGalleryComparison(["demo-0","demo-1"]);render(<Gallery/>);expect(await screen.findByRole("dialog",{name:"Comparar mídias"})).toBeInTheDocument();expect((await screen.findAllByText("IMG_2401.JPG")).length).toBeGreaterThan(0)});
});
