import { cleanup, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import Gallery, { resetGallerySession } from "./Gallery";
import { api } from "./api";

describe("galeria em escala",()=>{
 afterEach(()=>{cleanup();resetGallerySession();localStorage.clear();vi.restoreAllMocks()});
 it("mostra indicadores e aplica filtros combinados",async()=>{const user=userEvent.setup();const spy=vi.spyOn(api,"gallery");render(<Gallery/>);expect(await screen.findByText("18")).toBeInTheDocument();expect(screen.getByText("Em várias origens")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:/Filtros/}));await user.selectOptions(screen.getByLabelText("Tipo"),"video");await user.selectOptions(screen.getByLabelText("Câmera"),"DJI Mini 4 Pro");await user.click(screen.getByRole("button",{name:"Aplicar filtros"}));await waitFor(()=>expect(spy).toHaveBeenLastCalledWith(expect.objectContaining({mediaType:"video",camera:"DJI Mini 4 Pro"}),undefined,100));expect(screen.getByText(/resultados/)).toBeInTheDocument()});
 it("mantém o cabeçalho natural e não polui o grid com proteção pendente",async()=>{render(<Gallery/>);expect((await screen.findAllByText(/^[A-ZÁÉÍÓÚÂÊÔÃÕÇ][^\n]+ de \d{4}$/)).length).toBeGreaterThan(0);expect(screen.queryByText("Proteção pendente")).not.toBeInTheDocument()});
 it("usa a miniatura real também no preview",async()=>{const user=userEvent.setup();vi.spyOn(api,"thumbnail").mockResolvedValue("data:image/jpeg;base64,AA==");render(<Gallery/>);await user.click(await screen.findByRole("button",{name:"Abrir detalhes de IMG_2401.JPG"}));expect(await screen.findByText("SHA-256")).toBeInTheDocument();const previews=await screen.findAllByRole("img",{name:"Prévia de IMG_2401.JPG"});expect(previews).toHaveLength(2);expect(previews[1]).toHaveAttribute("src","data:image/jpeg;base64,AA==")});
 it("continua navegável enquanto a miniatura é produzida em background",async()=>{const user=userEvent.setup();const thumbnail=vi.spyOn(api,"thumbnail").mockResolvedValueOnce(null).mockResolvedValue("http://lumina-thumb.localhost/demo-1");render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:/Filtros/}));expect(screen.getByRole("button",{name:"Aplicar filtros"})).toBeEnabled();expect(await screen.findByRole("img",{name:"Prévia de IMG_2401.JPG"},{timeout:2000})).toHaveAttribute("src","http://lumina-thumb.localhost/demo-1");expect(thumbnail.mock.calls.length).toBeGreaterThanOrEqual(2)});
 it("alterna para lista e persiste a preferência",async()=>{const user=userEvent.setup();const first=render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:"Visão em lista"}));expect(document.querySelector(".virtual-gallery.list")).toBeInTheDocument();expect(localStorage.getItem("lumina-view")).toBe("list");first.unmount();render(<Gallery/>);await waitFor(()=>expect(document.querySelector(".virtual-gallery.list")).toBeInTheDocument())});
 it("seleciona mídias e aplica tag em lote",async()=>{const user=userEvent.setup();const apply=vi.spyOn(api,"applyTag");render(<Gallery/>);await screen.findByText("IMG_2401.JPG");await user.click(screen.getByRole("button",{name:"Selecionar IMG_2401.JPG"}));expect(screen.getByText("1 selecionadas")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Aplicar tag"}));await user.type(screen.getByLabelText("Nome da tag"),"favorita");await user.click(screen.getByRole("button",{name:"Aplicar"}));await waitFor(()=>expect(apply).toHaveBeenCalledWith("favorita",["demo-1"]));expect(await screen.findByRole("status")).toHaveTextContent("1 mídias atualizadas")});
});
