export type View = "dashboard" | "library" | "review" | "sources" | "duplicates" | "albums" | "activity" | "protection";
export type ProtectionState = "source_only" | "consolidated" | "replica_verified" | "stale" | "error";

export interface LibraryConfig { id: string; name: string; masterPath: string; backupPath: string; createdAt: string }
export interface DashboardBreakdown{key:string;items:number;bytes:number}
export interface DashboardStorage{masterTotalBytes:number;masterUsedBytes:number;masterFreeBytes:number;libraryBytes:number;cacheBytes:number;temporaryBytes:number;backupTotalBytes:number;backupUsedBytes:number;backupFreeBytes:number;pendingBackupBytes:number;projectedBackupFreeBytes:number;reserveBytes:number;estimatedAdditionalItems:number;averageAssetBytes:number;p90AssetBytes:number;backupAvailable:boolean}
export interface DashboardTechnical{enriched:number;complete:number;partial:number;preservation:number;unknown:number;mismatches:number;codecKnown:number;codecMissing:number;thumbnailsReady:number;thumbnailsPending:number;thumbnailsFailed:number;metadataComplete:number;reviewItems:number;reviewBytes:number}
export interface DashboardBenchmark{jobId:string;items:number;bytes:number;analysisMs:number;hashingMs:number;copyMs:number;thumbnailsMs:number;hashWorkers:number;hashedBytes:number;deferredHashItems:number;cacheHits:number}
export interface DashboardStats { totalAssets:number;photos:number;videos:number;bytes:number;protected:number;pending:number;duplicateGroups:number;duplicateBytes:number;reclaimableBytes:number;errors:number;offlineSources:number;oldest?:string;newest?:string;oldestPhoto?:string;newestPhoto?:string;oldestVideo?:string;newestVideo?:string;masterAvailableBytes:number;backupAvailableBytes:number;types:DashboardBreakdown[];years:DashboardBreakdown[];months:DashboardBreakdown[];protection:DashboardBreakdown[];protectionYears?:DashboardBreakdown[];protectionSources?:DashboardBreakdown[];cameras:DashboardBreakdown[];formats:{key:string;label:string;family:string;support:string;items:number;bytes:number}[];codecs?:DashboardBreakdown[];storage?:DashboardStorage;technical?:DashboardTechnical;sources:{id:string;name:string;available:boolean;items:number;bytes:number}[];insights:{kind:string;severity:string;title:string;detail:string;value:number;bytes:number;action:View;actionLabel:string;confidence:string;reason:string}[];latestBenchmark?:DashboardBenchmark;recentBenchmarks?:DashboardBenchmark[];snapshotGeneratedAt:string;stale:boolean;timings:{section:string;milliseconds:number}[] }
export interface Source { id: string; name: string; path: string; volumeLabel: string; available: boolean; lastScan?: string; assetCount: number }
export interface ReviewSummary {reviewLater:number;suspiciousDates:number;missingPreviews:number;incompleteMetadata:number;pendingProtection:number;undecidedDuplicates:number;technicalFailures:number}
export interface LibraryHealth{overall:"healthy"|"attention"|"error";checks:{key:string;label:string;state:"healthy"|"warning"|"error";detail:string}[];generatedAt:string}
export interface MediaAsset { id: string; filename: string; mediaType: "photo" | "video" | "raw"; extension: string; capturedAt: string; dateSource: string; dateSuspicious?: boolean; bytes: number; width?: number; height?: number; duration?: number; camera?: string; latitude?: number; longitude?: number; thumbnail?: string; masterPath: string; hash: string; protectionState: ProtectionState; occurrenceCount: number; sourceNames: string[]; tags: string[];favorite:boolean;rating:number;reviewLater:boolean;description:string }
export interface AssetDetails{camera?:string;detectedFormat?:string;mime?:string;container?:string;codec?:string;audioCodec?:string;frameRate?:number;bitrate?:number;pixelFormat?:string;lens?:string;iso?:number;aperture?:number;exposure?:string;focalLength?:number;orientation?:number;colorProfile?:string;supportLevel?:string;inventoryState?:string;inventoryError?:string;enrichedAt?:string}
export interface GalleryFilters { query:string; year?:number; dateFrom?:string; dateTo?:string; mediaType?:string; camera?:string; sourceId?:string; originalFolder?:string; extension?:string; hasLocation?:boolean; tagId?:string; albumId?:string; protectionState?:string; dateSuspicious?:boolean;favorite?:boolean;minimumRating?:number;reviewLater?:boolean }
export type GallerySort = "captured_desc"|"captured_asc"|"name_asc"|"name_desc"|"size_desc"|"size_asc";
export interface SavedView {id:string;name:string;filters:GalleryFilters;smartAlbum:boolean;createdAt:string;updatedAt:string}
export interface TagInfo{id:string;name:string;assetCount:number}
export interface FilterOption { value:string; label:string; count:number }
export interface GallerySummary { total:number; bytes:number; photos:number; videos:number; raw:number; protected:number; withLocation:number; duplicateAssets:number; favorites?:number; incompleteMetadata?:number; pendingProtection?:number; years:{year:string;count:number;bytes:number}[] }
export interface GalleryResult { assets:MediaAsset[]; matched:number; nextCursor?:string; summary:GallerySummary; options:{cameras:FilterOption[];sources:FilterOption[];extensions:FilterOption[];tags:FilterOption[];albums:FilterOption[]} }
export interface ThumbnailAudit { total:number;valid:number;missing:number;stale:number;corrupt:number;regenerated:number;failed:number }
export interface ThumbnailRepairProgress{running:boolean;processed:number;total:number;regenerated:number;failed:number}
export interface ImportIssue { kind: string; extension: string; items: number; bytes: number; message: string }
export interface ImportSummary { jobId: string; sourceId: string; sourcePath: string; discovered: number; newFiles: number; duplicates: number; invalid: number; requiredBytes: number; availableBytes: number; excluded: number; issues: ImportIssue[] }
export interface StoragePlan { masterRequiredBytes:number;backupRequiredBytes:number;reserveBytes:number;masterAvailableBytes:number;backupAvailableBytes:number;sameVolume:boolean;canConsolidate:boolean;canProtect:boolean;missingBytes:number;backupMissingBytes:number;selectedItems:number;selectedBytes:number;maximumSafeBytes:number;maximumSafeItems:number }
export interface SelectionResult {selectedItems:number;selectedBytes:number;pendingItems:number;pendingBytes:number}
export interface ProtectionQueueStats {pending:number;processing:number;completed:number;failed:number;pendingBytes:number}
export interface MigrationProgress {id:string;oldMaster:string;newMaster:string;state:string;processedItems:number;totalItems:number;processedBytes:number;totalBytes:number;lastError?:string}
export interface JobProgress { jobId: string; state: string; stage: string; currentFile?: string; processedItems: number; totalItems: number; processedBytes: number; totalBytes: number; imported: number; duplicates: number; excluded: number; failed: number; stagePercent:number; overallPercent:number; bytesPerSecond?:number; estimatedSecondsRemaining?:number; libraryState:string; backupState:string }
export interface RecoverableJob { jobId:string; sourcePath:string; state:string; stage:string; interruptionReason?:string; updatedAt:string }
export interface JobEventPage { events:ImportEvent[]; nextCursor:number }
export interface ReportExport { path:string; rows:number }
export interface ImportEvent { id: number; jobId: string; at: string; path: string; state: string; details: string }
export interface DuplicateGroup { assetId:string;hash: string; filename: string; bytes: number; additionalBytes: number; reclaimableBytes: number; safety: "eligible_for_review"|"protection_required"; occurrences: { id:string;source: string; path: string;decision?:"keep"|"review"|"remove_candidate" }[];decision?:"keep_all"|"review"|"remove_candidates" }
export interface DuplicateStatus{state:"not_analyzed"|"none_found"|"found"|"failed";catalogAssets:number;exactGroups:number;occurrences:number;connectedSources:number;totalSources:number;lastScan?:string}
export interface CleanupPlanItem{occurrenceId:string;assetId:string;filename:string;source:string;path:string;bytes:number;eligibility:"eligible"|"blocked";reason:string}
export interface CleanupPlan{id:string;state:string;groups:number;candidates:number;bytes:number;blocked:number;items:CleanupPlanItem[];createdAt:string}
export interface Album { id: string; name: string; assetCount: number; cover?: string }
export interface JobOverview { jobId:string; sourceName:string; sourcePath:string; state:string; stage:string; processedItems:number; totalItems:number; processedBytes:number; totalBytes:number; overallPercent:number; bytesPerSecond?:number; estimatedSecondsRemaining?:number; imported:number; duplicates:number; excluded:number; failed:number; createdAt:string; updatedAt:string; interruptionReason?:string }
export interface BatchResult { affected:number }
